<a href="https://colab.research.google.com/github/OberCoder/mis433/blob/main/Assignment_Python_Basics_COMPLETE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment: Python Basics
We assume you are using Python 3 in this course.

## Question 1

You've learned different data types in Python. Now, let's test your knowledge.

You need to use to format strings.

Write a program using the "f-strings" (https://realpython.com/python-f-strings/) and user input function to convert temperatures from Fahrenheit to Celsius. [Formula: Celsius = (Fahrenheit – 32)*5/9]

Hint: you may need int() or float() function

An example program output:
```
Please enter the temperature in Fahrenheit: 140
140F is 60.0 in Celsius.
```

In [ ]:
# an example of f-strings and user input function
username = input('What\'s your name? ')
print(f'Welcome, {username}!')

In [ ]:
# complete your program here
f = input('Please enter the temperature in Fahrenheit: ')
f = int(f)
print(f)

#Celsius = (Fahrenheit – 32)*5/9
c = (f - 32) * 5/9

print(f'{f}F is {c} in Celsius. ')
#print(str(f)+'F is '+str(c)+' in Celsius. ')

Please enter the temperature in Fahrenheit: 140
140
140F is 60.0 in Celsius. 


Now, do the oppsoite by convert temperatures from Celsius to Fahrenheit.
Another example:
```
Please enter the temperature in Celcius: 60
60C is 140.0 in Fahrenheit.
```

In [ ]:
# complete your program here
c = input('Please enter the temperature in Celsius:  ')
c = int(c)
print(c)

f = (c / (5/9)) + 32

print(f'{c}C is {f} in Fahrenheit.  ')

Please enter the temperature in Celsius:  60
60
60C is 140.0 in Fahrenheit.  


Next, let's make it a bit challenging by adding conditional statements to convert temperatures to and from Celsius, Fahrenheit. [Formula: Celsius/5 = (Fahrenheit – 32)/9]

An example program output:
```
Please enter the temperature: 60
Is this in Celsius or Fahrenheit? C
60C is 140 in Fahrenheit
```

Another example:
```
Please enter the temperature: 140
Is this Celsius or Fahrenheit? F
140F is 60 in Celsius
```

In [ ]:
# complete your program here
d = input('Please enter the temperature: ')
m = input('Is this in Celsius or Fahrenheit? ')
d = int(d)
f = (c / (5/9)) + 32
c = (f - 32) * 5/9
if m == "C":
  print(f'{d}C is {f} in Fahrenheit')
else:
  print(f'{d}F is {c} in Celsius')

Please enter the temperature: 140
Is this in Celsius or Fahrenheit? F
140F is 60.0 in Celsius


## Question 2

Have some fun with strings.

In [ ]:
sentence = "Talk is cheap. Show me the code - Linus Torvalds"

In [ ]:
# Find the length of this sentence.
len(sentence)

48

In [ ]:
# Convert the whole string to lower case.
print(sentence.lower())

talk is cheap. show me the code - linus torvalds


In [ ]:
# Extract a substring from the 10th character from left to the 10th character from right.
print(sentence[9:-9])

heap. Show me the code - Linus


In [ ]:
# Split the sentence into a list of substrings by space ' '.
print(sentence.split())

['Talk', 'is', 'cheap.', 'Show', 'me', 'the', 'code', '-', 'Linus', 'Torvalds']


In [ ]:
# Given the sentence, output a list of words in lowercase (without symbols such as '.' and '-').
print(sentence.lower().replace('. ', ' ').replace(' -', ''))

talk is cheap show me the code linus torvalds


In [ ]:
# Count the total number of vowels in the sentence.
vowels = ['a','e','i','o','u']
#vowels = 'aeiou'
total = 0
for v in vowels:
  total += sentence.lower().count(v)
print(total)

13


In [ ]:
# Find the positions (indexes) of all vowels in the sentence.
positions = []
for i in range(len(sentence)):
    if sentence[i].lower() in vowels:
      positions.append(i)
print(positions)

[1, 5, 10, 11, 17, 21, 25, 28, 30, 35, 37, 41, 44]


## Question 3

Review list comprehension if needed: https://realpython.com/list-comprehension-python/

The formula for list comprehension is: `new_list = [expression for member in iterable (if conditional)]`

You need to do the following:

In [ ]:
# Use a loop to create a list of 5 cube numbers and print the list：[0, 1, 8, 27, 64]
cubes = [0, 1, 8, 27, 64]
print(cubes)

[0, 1, 8, 27, 64]


In [ ]:
# Use list comprehension to create the same list
new_list = [x**3 for x in range(5)]
print(new_list)

[0, 1, 8, 27, 64]


In [ ]:
# Find the postions (indexes) of all vowels in a sentence using list comprehension
sentence = "Toto, I\'ve a feeling we\'re not in Kansas anymore. - THE WIZARD OF OZ (1939)"
oz_list = [i for i in range(len(sentence)) if sentence[i].lower() in vowels]
print(oz_list)

[1, 3, 6, 9, 11, 14, 15, 17, 22, 25, 28, 31, 35, 38, 41, 45, 47, 54, 57, 59, 63, 66]


In [ ]:
# Use a loop to create a list of first n numbers in the Fibonacci sequence
# [0, 1, 1, 2, 3, 5, 8, ...]
fibonacci = []
n = input('How many numbers do you want? ')

# add your code here


## Question 4

This question is about Python dictionary.

|Vaccine|Efficacy|
|-----|-------|
|Pfizer|95%|
|Moderna|95%|
|AstraZeneca|72%|
|Johnson & Johnson|66%|

Source: https://www.biospace.com/article/comparing-covid-19-vaccines-pfizer-biontech-moderna-astrazeneca-oxford-j-and-j-russia-s-sputnik-v/

In [ ]:
# Create a dictionary to save the data of vaccines and their efficacy. (save 95% as 0.95)
v_dict = {'Pfizer' : '.95', 'Moderna' : '.95', 'AstraZeneca' : '.72', 'Johnson & Johnson' : '.66'}
print(v_dict['Pfizer'])

.95


In [ ]:
v = input('Which vaccine? ')
# print the efficacy of the vaccine
print(v_dict[v])

Which vaccine? Moderna
.95


In [ ]:
# add another vaccine 'Sputnik V' with 91.4% efficacy rate to the dictionary
v_dict['Sputnik V'] = '.914'
print(v_dict)

{'Pfizer': '.95', 'Moderna': '.95', 'AstraZeneca': '.72', 'Johnson & Johnson': '.66', 'Sputnik V': '.914'}


In [ ]:
# add another vaccine 'Sinovac' with 50.38% efficacy rate to the dictionary
v_dict['Sinovac'] = '.5038'
print(v_dict)

{'Pfizer': '.95', 'Moderna': '.95', 'AstraZeneca': '.72', 'Johnson & Johnson': '.66', 'Sputnik V': '.914', 'Sinovac': '.5038'}


In [ ]:
# Print vaccines with efficacy lower than 90%.
for vaccine, efficacy in v_dict.items():
  if float(efficacy) < 0.90:
    print(vaccine, efficacy)

AstraZeneca .72
Johnson & Johnson .66


In [ ]:
# delete the Sinovac vaccine from the dictionary.
del v_dict['Sinovac']
print(v_dict)

{'Pfizer': '.95', 'Moderna': '.95', 'AstraZeneca': '.72', 'Johnson & Johnson': '.66', 'Sputnik V': '.914'}


In [ ]:
#Count the occurrence of each alphabet (no space ' ') in this sentence.
sentence = 'the quick brown fox jumps over the lazy dog'
new_sentence = (sentence.replace(' ', ''))
print(len(new_sentence))
# Save the result in a dictionary
ch_dict = {new_sentence}
# Use a loop to iterate all characters
# add your code here

# print the dictionary
print(ch_dict)

35
{'thequickbrownfoxjumpsoverthelazydog'}


## Quesion 5

Next, we will practice with Numpy arrays.  

In [ ]:
import numpy as np

In [ ]:
# create a 1-D array of first 20 positive even numbers (starting with 2)
print(np.array(range(2, 42, 2)))

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40]


In [ ]:
# create a 1-D array of first 20 positive odd numbers (starting with 1)
print(np.array(range(1, 42, 2)))

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41]


In [ ]:
# create a 10x10 array in the following format:
# first row: [0,1,...,9]
# second row: [10,11,...,19]
# ...
# tenth row: [90,91,...,99]
print(np.array(range(100)).reshape(10, 10))

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [ ]:
# Create a 10x10 array of normally distributed random values
# with mean 0 and standard deviation 1
M = np.random.normal(0, 1, (10, 10))
print(M)

[[-0.14181913  1.2767968   1.63611246 -1.03034799 -0.57110405  0.55404581
   0.04727811 -0.56603006 -0.32518001 -0.41405581]
 [ 0.32652859  1.72751214  2.04645958  0.34221995  0.47167057 -0.12130405
  -0.64878332 -1.19484231  0.38671745  2.03877334]
 [-0.64426561  0.0805638  -2.12718473  0.85071246  0.46147037  0.67001589
  -0.18817904 -1.03547572  0.77770592 -0.53566968]
 [-0.22862394  0.78938199 -0.03282877 -1.46843304 -1.01962046  0.70079685
  -0.05560523 -0.79533448  0.74673283  2.20762259]
 [ 0.50173015 -0.23888347  0.10779202  0.18382676  0.62693463  0.31688967
   1.10557122  1.10708982  1.65418432  0.32716286]
 [-0.722948   -0.2839648   0.00396745 -0.73316662  0.88914446 -0.45471732
  -0.13734337 -1.36887245 -0.2863636   0.10008694]
 [ 0.57016428 -0.41061602 -0.92946552 -1.38439383 -0.06261306  1.4453708
  -0.16168577 -2.24041684 -1.39565659  0.47185893]
 [-1.40430484 -0.63345208 -1.32595246 -0.68952263  0.62204099 -0.75817557
   0.12001004  0.6831208  -0.66021101  1.26566717]
 

In [ ]:
# Count the numbers in M with an absolute value greater than 1.
print(np.sum(abs(M) > 1))

29


In [ ]:
# Reference: https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html

# Input the number of rows (input an integer >= 3)


# Input the number of rows (input another integer >= 3)


# Hint: you may want to use the function int().
r = int(input('Row count: '))
c = int(input('column count: '))
# Create a r x c array of random integers between 10 (inclusive) and 20 (exclusive).

arr = np.random.randint(10, 20, (r, c))
print(arr)

Row count: 5
column count: 3
[[12 16 12]
 [14 13 12]
 [11 18 15]
 [11 19 14]
 [11 17 11]]


In [ ]:
# output the element in the first row and the third column
print(arr[0, 2])

12


In [ ]:
# output the element in the second row and the last column
print(arr[1, 2])

12


In [ ]:
# output the second row of the array
print(arr[1, ])

[14 13 12]


In [ ]:
# output the second last row of the array
print(arr[3:4, ])

[[11 19 14]]


In [ ]:
# output the second column of the array
print(arr[:, 1])

[16 13 18 19 17]


In [ ]:
# output the second last column of the array
print(arr[:, 1])

[16 13 18 19 17]


In [ ]:
# output the upper-left 3x3 sub-array
print(arr[0:3, 0:3])

[[12 16 12]
 [14 13 12]
 [11 18 15]]


In [ ]:
# output the bottom-left 3x3 sub-array
print(arr[2:5, 0:3])

[[11 18 15]
 [11 19 14]
 [11 17 11]]


In [ ]:
# output the upper-right 3x3 sub-array
print(arr[0:3, 0:3])

[[12 16 12]
 [14 13 12]
 [11 18 15]]


In [ ]:
# output the bottom-right 3x3 sub-array
print(arr[2:5, 0:3])

[[11 18 15]
 [11 19 14]
 [11 17 11]]


In [ ]:
# Create a 1-D array from 1 to 50 (inclusive)
A = np.array(range(1, 51))

# Reshape A to a 5x10 array in the following format:
# first row: [1,...,10]
# second row: [11,...,20]
# ...
# fifth row: [41,...,50]
print(A.reshape(5, 10))

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]]


In [ ]:
# add a row [51,...,60] to A
A = np.append(A, range(51, 61))
print(A.reshape(6, 10))


[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]
 [51 52 53 54 55 56 57 58 59 60]]


In [ ]:
# split the new A (6x10) to two 3x10 arrays A1 and A2
A1, A2 = np.split(A, 2)
print(A1.reshape(3, 10))
print(A2.reshape(3, 10))

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]
[[31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]
 [51 52 53 54 55 56 57 58 59 60]]


In [ ]:
# Add 10 to each element of A
A1 = np.append(A, range(31, 41))
print(A1)
A2 = np.append(A, range(61, 71))
print(A2)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 31 32 33 34 35 36 37 38 39 40]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [ ]:
# Calculate the square root of each element in A
print(np.sqrt(A))

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766 3.31662479 3.46410162
 3.60555128 3.74165739 3.87298335 4.         4.12310563 4.24264069
 4.35889894 4.47213595 4.58257569 4.69041576 4.79583152 4.89897949
 5.         5.09901951 5.19615242 5.29150262 5.38516481 5.47722558
 5.56776436 5.65685425 5.74456265 5.83095189 5.91607978 6.
 6.08276253 6.164414   6.244998   6.32455532 6.40312424 6.4807407
 6.55743852 6.63324958 6.70820393 6.78232998 6.8556546  6.92820323
 7.         7.07106781 7.14142843 7.21110255 7.28010989 7.34846923
 7.41619849 7.48331477 7.54983444 7.61577311 7.68114575 7.74596669]


In [ ]:
# Above, we should have created a 10x10 array M of normally distributed random values
# with mean 0 and standard deviation 1
M.shape

(10, 10)

In [ ]:
# Print the mean, standard devietion of all numbers in M
print(np.mean(M))
print(np.std(M))

0.0016731332393648169
0.9348550165449684


In [ ]:
# Print the maximumn, 3rd quartile, median, 1st quartile, and minimum in M
print(np.max(M))
print(np.percentile(M, 75))
print(np.median(M))
print(np.percentile(M, 25))
print(np.min(M))

2.2076225908141347
0.6404212911465156
-0.04421700224962736
-0.6453950403187488
-2.2404168425898012
